### ISSUE TITLE
Conditional compilation based on imports (not an issue)

### ISSUE THREAD

**Issue by DevinR528** [mtkennerly/realia#2]
I saw you had mentioned something about extending `realia` to also conditionally compile based on crates. Today I saw this crate https://crates.io/crates/proc-macro-crate which at least accesses the `Cargo.toml` file? Just thought it __might__ be helpful :shrug:.

Edit: Ahh "downstream" dependencies, so this is the wrong way sorry nvm.

**Comment by mtkennerly** [comment]
Actually, that just gave me an idea. My previous attempts focused on using a build.rs to generate static crate info, but I see that proc-macro-crate checks `std::env::var("CARGO_MANIFEST_DIR")` in the proc macro itself. I checked, and that gives me the downstream crate's manifest dir, not Realia's, which I should then be able to pass to the `cargo metadata` command. That might just work!

**Comment by mtkennerly** [comment]
Success \:D I just published v0.2.0, which includes these new attributes:

* `#[realia::dep("your-crate", "a-dependency")]`
* `#[realia::dep("your-crate", "a-dependency", "1.2.3")]`
* `#[realia::dep_since("your-crate", "a-dependency", "1.2.3")]`
* `#[realia::dep_before("your-crate", "a-dependencyo", "1.2.3")]`
* `#[realia::dep_from_registry("your-crate", "a-dependency")]`

The only caveats are:

* You have to specify your crate's name, since the implementation relies on `CARGO_MANIFEST_DIR`. Otherwise, you'd get different results for `cargo build` in your project vs a downstream project.
* I don't know how to reliably detect which features are enabled, so optional dependencies are ignored for now. When I'm assembling the arguments for `cargo metadata`, I only get to see how rustc was invoked, not how Cargo was invoked.

**Comment by DevinR528** [comment]
Nice!! Glad it worked out.
